### ISSUE TITLE
Array values may contain duplicate when merged

### ISSUE THREAD

**Issue by noook** [unjs/defu#136]
### Environment

defu@6.1.4

### Reproduction

```ts
defu({ array: ["a", "b"] }, { array: ["c", "d", "a"] });
```

outputs

```json
{
  "array": ["a", "b", "c", "d", "a"]
}
```

### Describe the bug

When providing a default value for an array, as a user, I expect the array to be duplicate-free when they are merged.

A PR is already available.

### Additional context

The issue was noticed when doing this:

```ts
config = defu(config, useRuntimeConfig(event).oauth?.bluesky, { scope: [] }) as OAuthBlueskyConfig
```

It caused an error due to the OAuth provider throwing an error due to duplicate scopes

**Comment by pi0** [comment]
Arrays in JavaScript can contain duplicate values.

A custom merger can dedup them based on usage needs (dedup based on keys or ref with a Set, etc) -- it is unsafe to do this by default in defu.

**Comment by noook** [comment]
Thanks for the confirmation, this is what I guessed.
