### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by datikken** [unjs/defu#30]
Hi there i guess it's related to [https://github.com/nuxt-community/axios-module/commit/a9e4867587cd60a25aca441159938495d41755c9](url)

**Comment by datikken** [comment]
https://gyazo.com/be3602a6beea55ca4f9942063a0876eb

**Comment by pi0** [comment]
Dup of https://github.com/nuxt-community/axios-module/issues/501. Lets track it there :)
