### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by camohub** [unjs/defu#31]
Hi can you tell me please how to fix this error:

**Cannot assign to read only property 'exports' of object '#<Object>'**

This library is used by some third party lib but as you can see the application build is not able to work with this type of module export. Its a Nuxt application but this error start to appear as I install some Babel packages. Here is detailed description: https://stackoverflow.com/questions/70785689/nuxt-with-babel-throws-uncaught-typeerror-cannot-assign-to-read-only-property

Thanks.

**Comment by pi0** [comment]
Hi dear @camohub. I hope with v5 and v6 of defu, your problem is resolved. However if exists I'm afraid is a configuration error with babel.
