### ISSUE TITLE
bug: unexpected type when defu two arrays

### ISSUE THREAD

**Issue by Cheng-DX** [unjs/defu#49]
When I use:
```js
const a = defu([1, 2], [])
```
The type of `a` will be `object` not array. That cause I cannot use `map` or any other array's function to `a`
Is that a feature or a bug?

**Comment by danielroe** [comment]
This isn't just the type, it's what defu would actually do. It expects to receive objects.

```bash
> require('defu').defu([1, 2], [3])
{ '0': 1, '1': 2 }
```
