### ISSUE TITLE
Defu is not a function

### ISSUE THREAD

**Issue by kaviraj-soni** [unjs/defu#53]
You should roll back to the old version (6.1.0) if the fix will take time.
You have released breaking changes as a minor version update (6.1.0 to 6.1.1)
Our production build has been stopped for the last 6 hrs
there is a huge revenue impact because of this

Your other module rc9 uses defu and it is breaking our nuxt build as rc9 is used during the build process

Please reach out if you need any help

**Comment by pi0** [comment]
Would you please provide a reproduction? 🙏🏼

**Comment by kaviraj-soni** [comment]
> Would you please provide a reproduction? 🙏🏼

in a lot of packages used by NuxtJS
the rc9 version "^1.2.0" was mentioned
and due to that when we do npm install it picked up the rc9 version 1.2.3
and since rc9 1.2.3 moved from defu 6.1.0 to 6.1.1 ( breaking changes ), the files in nuxt build which were using defu the old way stopped working causing the build to fail
hope this answers your question

**Comment by pi0** [comment]
I checked the output defu has not breaking changes. But rc9 is downgraded to 1.2.0 (releasing 2.0.0 for Nuxt3 only). 

Do you mind to recreate your lockfile if issue is solved?

**Comment by pi0** [comment]
Thanks for confirming. If works fine i think we can close this issue?

BTW are you using Nuxt 2 or 3?

**Comment by kaviraj-soni** [comment]
> Thanks for confirming. If works fine i think we can close this issue?
> 
> BTW are you using Nuxt 2 or 3?

Yes, we can close this issue now
We are using Nuxt 2
