### ISSUE TITLE
Defu is not a function

### ISSUE THREAD

**Issue by emiltsang** [unjs/defu#55]
The nuxt build keeps failing when rc9 is upgraded to 1.2.3, with error Defu is not a function.

Should I use "rc9": 1.2.2 to resolve the issue?
Since 1.2.2 depends on "defu": 6.1.0 instead of "defu": 6.1.1 that causing the build failure?

**Comment by Billybobbonnet** [comment]
Nuxt image is using also  rc9 `1.2.2` that refers to defu `6.1.1`. For the record: https://github.com/nuxt/image/issues/649

**Comment by NozomuIkuta** [comment]
@emiltsang @Billybobbonnet 

Are you still facing at this issue?

Nuxt 3 stable version now depends on `rc9@2.0.0`, which in turn depends on `defudefu@6.1.1`

**Comment by NozomuIkuta** [comment]
Let me close this issue for now, because I believe it's already resolved.
Please feel free to reopen this issue as needed.
