### ISSUE TITLE
Array merge order is unintuitive

### ISSUE THREAD

**Issue by dword-design** [unjs/defu#98]
### Environment

Node.js: v18.12.1
defu: 6.1.2

### Reproduction

https://github.com/dword-design/demo-defu-array-merge

### Describe the bug

`defu({ plugins: ['local 1', 'local 2'] }, { plugins: ['inherited 1', 'inherited 2'] })`

Expected: `{ plugins: ['inherited 1', 'inherited 2', 'local 1', 'local 2'] }`.
Actual: `{ plugins: ['local 1', 'local 2', 'inherited 1', 'inherited 2'] }`.

I would expect the order in the array to always be parent first and then child. Has direct implications if you have a plugin or module system where the order is important.

**Comment by pi0** [comment]
Hi & sorry for responding late. Actually, it is kinda of a standard within unjs ecosystem that arrays are sorted from explicit to defaults (top to down) and also it is consistent with defu arguments order.

I respect that might not be of your preference or expectation but even if we want to make a change like this today, the ecosystem breaking changes cost (even with a major version of defu) would be so high that it is not feasible.

I think best resort for any custom solution would be using a custom defu merger.

**Comment by pi0** [comment]
There might be some upstream reasons to do this. Nothing we can change easily for defu defult bahavior, but we can introduce a new option for custom merger in c12 as mentioned and possibly consider it for nuxt options/plugins/modules/etc merging if breaking chance were acceptable to reverse order.

**Comment by ojvribeiro** [comment]
The first thing that comes to my mind is `tailwind-merge`, which uses this order that I also consider more intuitive (eg: `twMerge(lower_priority_param, higher_priority_param)`), just like how CSS works, what comes after overrides the ones before them. I understand tho, that changing the default behaviour now is not a good idea.

**Comment by pi0** [comment]
@dword-design Sorry but no. This is an unnecessary action and a major version won't change the ecosystem fragmentation consequences, we can't change `defu` function behavior.

I am up to introduce a new `defuReverse` that does both since now we have named exports btw.

**Comment by dword-design-honestly** [comment]
@pi0 What do you mean with "ecosystem fragmentation consequences"? A new export would make sense to me. Would it be the same like the default one and only changes the array merge order?

**Comment by dword-design-honestly** [comment]
Why at once? Then can be upgraded each at a time like it's usually done with major upgrades.

**Comment by pi0** [comment]
- new export: yes, please feel free to open new proposal to discuss 
- breaking default export behavior, sorry no
